name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node modules
      run: npm ci

    - name: Build next app
      run: npm run build

    outputs:
      build_status: ${{ job.status }}